apiVersion: 1

datasources:
  - name: observability-platform-logs
    type: loki
    uid: obs-loki
    access: proxy
    url: http://backend:8080
    isDefault: false
    editable: false
    jsonData:
      maxLines: 1000
