apiVersion: 1

datasources:
  - name: observability-platform
    type: prometheus
    uid: obs-prometheus
    access: proxy
    url: http://backend:8080
    isDefault: true
    editable: false
    jsonData:
      timeInterval: "5s"
